# Generated by Django 3.1.2 on 2020-11-04 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_document_refreshDate', models.DateTimeField(blank=True, null=True, verbose_name='Last Document Refresh Date')),
                ('last_tmpResult_refreshDate', models.DateTimeField(blank=True, null=True, verbose_name='Last Temporary Results Refresh Date')),
                ('last_aggregate_refreshDate', models.DateTimeField(blank=True, null=True, verbose_name='Last Aggregates Refresh Date')),
            ],
            options={
                'db_table': 'app_parameters',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'domain',
            },
        ),
        migrations.CreateModel(
            name='DomainList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('public', models.BooleanField()),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date creation')),
                ('date_modification', models.DateTimeField(auto_now=True, null=True, verbose_name='Date modification')),
            ],
            options={
                'db_table': 'domain_list',
            },
        ),
        migrations.CreateModel(
            name='GenericSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date creation')),
                ('date_modification', models.DateTimeField(auto_now=True, null=True, verbose_name='Date modification')),
            ],
            options={
                'db_table': 'generic_search',
            },
        ),
        migrations.CreateModel(
            name='GoogleResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(max_length=200)),
                ('rankn', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=2000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_google', models.DateTimeField(blank=True, null=True, verbose_name='Date Google')),
                ('date_scrap', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Scrapped')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.domain')),
            ],
            options={
                'db_table': 'google_result',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('label', models.CharField(max_length=200)),
                ('extension', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date creation')),
                ('date_modification', models.DateTimeField(auto_now=True, null=True, verbose_name='Date modification')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date creation')),
                ('generic_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.genericsearch')),
                ('google_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.googleresult')),
            ],
            options={
                'db_table': 'search_result',
            },
        ),
    ]
