# Generated by Django 3.1.2 on 2020-11-04 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0003_focuslist_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='focuslist',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='text.focuslist'),
        ),
    ]
