# Generated by Django 3.1.2 on 2020-11-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0004_focuslist_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='focuslist',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
