# Generated by Django 3.1.2 on 2020-11-05 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0007_auto_20201105_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('label', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='text.domain'),
        ),
        migrations.AddField(
            model_name='genericsearch',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='text.domain'),
        ),
        migrations.AddField(
            model_name='genericsearch',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='text.language'),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default=None, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='text.language'),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='text.language'),
        ),
        migrations.AlterField(
            model_name='googleresult',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='text.domain'),
        ),
        migrations.AlterField(
            model_name='tmpgoogleresult',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='text.domain'),
        ),
        migrations.CreateModel(
            name='ProjectSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('exact_expression', models.BooleanField()),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date creation')),
                ('date_modification', models.DateTimeField(auto_now=True, null=True, verbose_name='Date modification')),
                ('generic_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.genericsearch')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.project')),
            ],
            options={
                'db_table': 'project_search',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='text.status'),
            preserve_default=False,
        ),
    ]
