# Generated by Django 3.1.2 on 2020-11-05 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0009_auto_20201105_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleresult',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tmpgoogleresult',
            name='description',
        ),
    ]
