# Generated by Django 3.1.2 on 2020-11-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0010_auto_20201105_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleresult',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='tmpgoogleresult',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
