# Generated by Django 3.1.2 on 2020-11-05 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0011_auto_20201105_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFocusList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('focus_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.focuslist')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.project')),
            ],
            options={
                'db_table': 'project_focus_list',
            },
        ),
    ]
