# Generated by Django 3.1.2 on 2020-11-05 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0012_projectfocuslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericsearch',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='text.domain'),
        ),
        migrations.AlterField(
            model_name='genericsearch',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='text.language'),
        ),
    ]
