# Generated by Django 3.1.2 on 2020-11-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0015_auto_20201105_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='refresh_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
