# Generated by Django 3.1.2 on 2020-11-12 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0016_project_refresh_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleresult',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='text.language'),
        ),
        migrations.AddField(
            model_name='scrapaction',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='text.language'),
        ),
        migrations.AddField(
            model_name='tmpgoogleresult',
            name='action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='text.scrapaction'),
        ),
        migrations.AddField(
            model_name='tmpgoogleresult',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='text.language'),
        ),
    ]
