# Generated by Django 3.1.2 on 2020-11-12 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0017_auto_20201112_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapaction',
            name='generic_search',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='text.genericsearch'),
        ),
        migrations.AddField(
            model_name='scrapaction',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='text.project'),
        ),
    ]
